### ISSUE TITLE
[Feature] Roadmap to 12.0.0 Release

### ISSUE THREAD

**Issue by ChasarooniZ** [ChasarooniZ/More-Dynamic-Token-Rings#17]
- [ ] Tours Setup
- [ ] Better guide for making new tokens
- [ ] Custom Token Implementation
- [ ] Upgraded UI for menu
